// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: transfers/streams.proto

package pager_transfers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileStreamRequest_Type int32

const (
	ProfileStreamRequest_none         ProfileStreamRequest_Type = 0
	ProfileStreamRequest_profile_info ProfileStreamRequest_Type = 1 // информация о профиле
	ProfileStreamRequest_chats_role   ProfileStreamRequest_Type = 2 // информация о роли в чатах
)

// Enum value maps for ProfileStreamRequest_Type.
var (
	ProfileStreamRequest_Type_name = map[int32]string{
		0: "none",
		1: "profile_info",
		2: "chats_role",
	}
	ProfileStreamRequest_Type_value = map[string]int32{
		"none":         0,
		"profile_info": 1,
		"chats_role":   2,
	}
)

func (x ProfileStreamRequest_Type) Enum() *ProfileStreamRequest_Type {
	p := new(ProfileStreamRequest_Type)
	*p = x
	return p
}

func (x ProfileStreamRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileStreamRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_transfers_streams_proto_enumTypes[0].Descriptor()
}

func (ProfileStreamRequest_Type) Type() protoreflect.EnumType {
	return &file_transfers_streams_proto_enumTypes[0]
}

func (x ProfileStreamRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileStreamRequest_Type.Descriptor instead.
func (ProfileStreamRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{0, 0}
}

type ChatStreamRequest_Type int32

const (
	ChatStreamRequest_none      ChatStreamRequest_Type = 0
	ChatStreamRequest_chat_info ChatStreamRequest_Type = 1 // информация о чате
	ChatStreamRequest_messages  ChatStreamRequest_Type = 2 // сообщения в чате
)

// Enum value maps for ChatStreamRequest_Type.
var (
	ChatStreamRequest_Type_name = map[int32]string{
		0: "none",
		1: "chat_info",
		2: "messages",
	}
	ChatStreamRequest_Type_value = map[string]int32{
		"none":      0,
		"chat_info": 1,
		"messages":  2,
	}
)

func (x ChatStreamRequest_Type) Enum() *ChatStreamRequest_Type {
	p := new(ChatStreamRequest_Type)
	*p = x
	return p
}

func (x ChatStreamRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatStreamRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_transfers_streams_proto_enumTypes[1].Descriptor()
}

func (ChatStreamRequest_Type) Type() protoreflect.EnumType {
	return &file_transfers_streams_proto_enumTypes[1]
}

func (x ChatStreamRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatStreamRequest_Type.Descriptor instead.
func (ChatStreamRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{1, 0}
}

type ChatMemberRequest_Type int32

const (
	ChatMemberRequest_none        ChatMemberRequest_Type = 0
	ChatMemberRequest_member_info ChatMemberRequest_Type = 1 // информация об участнике
)

// Enum value maps for ChatMemberRequest_Type.
var (
	ChatMemberRequest_Type_name = map[int32]string{
		0: "none",
		1: "member_info",
	}
	ChatMemberRequest_Type_value = map[string]int32{
		"none":        0,
		"member_info": 1,
	}
)

func (x ChatMemberRequest_Type) Enum() *ChatMemberRequest_Type {
	p := new(ChatMemberRequest_Type)
	*p = x
	return p
}

func (x ChatMemberRequest_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatMemberRequest_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_transfers_streams_proto_enumTypes[2].Descriptor()
}

func (ChatMemberRequest_Type) Type() protoreflect.EnumType {
	return &file_transfers_streams_proto_enumTypes[2]
}

func (x ChatMemberRequest_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatMemberRequest_Type.Descriptor instead.
func (ChatMemberRequest_Type) EnumDescriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{2, 0}
}

type ProfileStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProfileStreamRequest) Reset() {
	*x = ProfileStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_streams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileStreamRequest) ProtoMessage() {}

func (x *ProfileStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_streams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileStreamRequest.ProtoReflect.Descriptor instead.
func (*ProfileStreamRequest) Descriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{0}
}

type ChatStreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId            string `protobuf:"bytes,1,opt,name=ChatId,proto3" json:"ChatId,omitempty"`                        // идентификатор чата
	RequestedMessages int64  `protobuf:"varint,2,opt,name=RequestedMessages,proto3" json:"RequestedMessages,omitempty"` // количество запрашивыемых сообщений
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_streams_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_streams_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{1}
}

func (x *ChatStreamRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatStreamRequest) GetRequestedMessages() int64 {
	if x != nil {
		return x.RequestedMessages
	}
	return 0
}

type ChatMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId string `protobuf:"bytes,1,opt,name=MemberId,proto3" json:"MemberId,omitempty"`
}

func (x *ChatMemberRequest) Reset() {
	*x = ChatMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transfers_streams_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMemberRequest) ProtoMessage() {}

func (x *ChatMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfers_streams_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMemberRequest.ProtoReflect.Descriptor instead.
func (*ChatMemberRequest) Descriptor() ([]byte, []int) {
	return file_transfers_streams_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

var File_transfers_streams_proto protoreflect.FileDescriptor

var file_transfers_streams_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x14, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x73, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a,
	0x0a, 0x14, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x68,
	0x61, 0x74, 0x73, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x10, 0x02, 0x22, 0x88, 0x01, 0x0a, 0x11, 0x43,
	0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x43, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x10, 0x02, 0x22, 0x52, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x22, 0x21, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x32, 0x8d, 0x02, 0x0a, 0x0c, 0x50, 0x61,
	0x67, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x55, 0x0a, 0x0d, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x30,
	0x01, 0x12, 0x4f, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x30, 0x01, 0x12, 0x55, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x70,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x30, 0x01, 0x42, 0x3c, 0x5a, 0x3a, 0x70, 0x61, 0x67,
	0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x3b, 0x70, 0x61, 0x67, 0x65, 0x72, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transfers_streams_proto_rawDescOnce sync.Once
	file_transfers_streams_proto_rawDescData = file_transfers_streams_proto_rawDesc
)

func file_transfers_streams_proto_rawDescGZIP() []byte {
	file_transfers_streams_proto_rawDescOnce.Do(func() {
		file_transfers_streams_proto_rawDescData = protoimpl.X.CompressGZIP(file_transfers_streams_proto_rawDescData)
	})
	return file_transfers_streams_proto_rawDescData
}

var file_transfers_streams_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transfers_streams_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transfers_streams_proto_goTypes = []interface{}{
	(ProfileStreamRequest_Type)(0), // 0: com.pager.api.ProfileStreamRequest.Type
	(ChatStreamRequest_Type)(0),    // 1: com.pager.api.ChatStreamRequest.Type
	(ChatMemberRequest_Type)(0),    // 2: com.pager.api.ChatMemberRequest.Type
	(*ProfileStreamRequest)(nil),   // 3: com.pager.api.ProfileStreamRequest
	(*ChatStreamRequest)(nil),      // 4: com.pager.api.ChatStreamRequest
	(*ChatMemberRequest)(nil),      // 5: com.pager.api.ChatMemberRequest
	(*TransferObject)(nil),         // 6: com.pager.api.TransferObject
}
var file_transfers_streams_proto_depIdxs = []int32{
	3, // 0: com.pager.api.PagerStreams.StreamProfile:input_type -> com.pager.api.ProfileStreamRequest
	4, // 1: com.pager.api.PagerStreams.StreamChat:input_type -> com.pager.api.ChatStreamRequest
	5, // 2: com.pager.api.PagerStreams.StreamChatMember:input_type -> com.pager.api.ChatMemberRequest
	6, // 3: com.pager.api.PagerStreams.StreamProfile:output_type -> com.pager.api.TransferObject
	6, // 4: com.pager.api.PagerStreams.StreamChat:output_type -> com.pager.api.TransferObject
	6, // 5: com.pager.api.PagerStreams.StreamChatMember:output_type -> com.pager.api.TransferObject
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transfers_streams_proto_init() }
func file_transfers_streams_proto_init() {
	if File_transfers_streams_proto != nil {
		return
	}
	file_transfers_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_transfers_streams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_streams_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatStreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transfers_streams_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transfers_streams_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfers_streams_proto_goTypes,
		DependencyIndexes: file_transfers_streams_proto_depIdxs,
		EnumInfos:         file_transfers_streams_proto_enumTypes,
		MessageInfos:      file_transfers_streams_proto_msgTypes,
	}.Build()
	File_transfers_streams_proto = out.File
	file_transfers_streams_proto_rawDesc = nil
	file_transfers_streams_proto_goTypes = nil
	file_transfers_streams_proto_depIdxs = nil
}
